### ISSUE TITLE
Kustomizer can't handle Kustomize overlays referring to sibling directories

### ISSUE THREAD

**Issue by lalloni** [stefanprodan/kustomizer#16]
When using kustomizer on a kustomization overlay which refers to bases located on sibling directories, it fails because it copies the directory to a temporary location and base relative paths are then broken.

For example, when kustomization.yaml listing "../../../../bases/main" as one of the bases gets copied to the temporary dir and tried to build using kustomize from there, kustomize fails because the base path is now wrong.

I think kustomizer should not copy the kustomization out of where it is supposed to be built.

**Comment by stefanprodan** [comment]
This has been fixed in v1.0, Kustomizer builds the overlay in-place.
