### ISSUE TITLE
Kustomizer leaks secrets on diff when using variable substitution in Flux

### ISSUE THREAD

**Issue by onedr0p** [stefanprodan/kustomizer#25]
An example:

Command:

```sh
kustomizer diff -f cluster/apps/velero/helm-release.yaml
```

Output, take notice $SECRET_DOMAIN and $NAS_ADDR

```
► HelmRelease/velero/velero drifted
  strings.Join({
  	... // 2008 identical bytes
  	"a21296fe3e8eb933f67f76adf4f429\n  creationTimestamp: \"2021-09-07T",
  	"15:11:54Z\"\n  finalizers:\n  - finalizers.fluxcd.io\n  generation: ",
- 	"9",
+ 	"10",
  	"\n  labels:\n    kustomize.toolkit.fluxcd.io/name: apps\n    kustom",
  	"ize.toolkit.fluxcd.io/namespace: flux-system\n  name: velero\n  na",
  	... // 157 identical bytes
  	"   sourceRef:\n        kind: HelmRepository\n        name: vmware-",
  	"tanzu-charts\n        namespace: flux-system\n      version: 2.23.",
- 	"8",
+ 	"6",
  	"\n  interval: 5m\n  values:\n    cleanUpCRDs: false\n    configurati",
  	"on:\n      backupStorageLocation:\n        bucket: velero\n        ",
  	"config:\n          publicUrl: https://s3.",
- 	"----------------THIS IS THE ACTUAL VALUE OF ${SECRET_DOMAIN}----------------",
+ 	"${SECRET_DOMAIN}",
  	"\n          region: us-east-1\n          s3ForcePathStyle: true\n  ",
  	"        s3Url: http://",
- 	"----------------THIS IS THE ACTUAL VALUE OF ${NAS_ADDR}----------------",
+ 	"${NAS_ADDR}",
  	":9000\n        name: default\n      extraEnvVars:\n        TZ: Amer",
  	"ica/New_York\n      provider: aws\n      resticTimeout: 6h\n      v",
  	... // 169 identical bytes
  	"age:\n      repository: ghcr.io/k8s-at-home/velero\n    initContai",
  	"ners:\n    - image: ghcr.io/k8s-at-home/velero-plugin-for-aws:v1.",
- 	"2.1",
+ 	"3.0",
  	"\n      imagePullPolicy: IfNotPresent\n      name: velero-plugin-f",
  	"or-aws\n      volumeMounts:\n      - mountPath: /target\n        na",
  	"me: plugins\n    kubectl:\n      image:\n        repository: ghcr.i",
  	"o/k8s-at-home/kubectl\n        tag: v1",
- 	".22.2",
+ 	".22.1",
  	"\n    metrics:\n      enabled: true\n      serviceMonitor:\n        ",
  	"enabled: true\n    resources:\n      limits:\n        memory: 1500M",
  	... // 1052 identical bytes
  }, "")
```

Also the description of this sub command says `"Diff compares the local Kubernetes manifests with the in-cluster objects and prints the YAML diff to stdout."` but the format is all messed up.

**Comment by stefanprodan** [comment]
Don't use Flux var substitution for secrets, use `valuesFrom` in HelmReleases, keep the secret in Git encrypted.

**Comment by onedr0p** [comment]
@stefanprodan that makes sense for helm releases, but what about something like an Ingress?

e.g. https://github.com/onedr0p/home-cluster/blob/main/cluster/apps/networking/traefik/dashboard/ingress.yaml#L15-L18

**Comment by onedr0p** [comment]
Sure, let me explain a bit. [Here](https://github.com/onedr0p/home-cluster/blob/main/cluster/base/cluster-secrets.sops.yaml) I have a file with several "global" secrets I want to use thru-out of kustomizations, k8s manifests and helm-releases.

I create a cert-manager `Certificate` [with a name of the domain](https://github.com/onedr0p/home-cluster/blob/main/cluster/apps/networking/wildcard-certificate/certificate.yaml#L5). This is useful if I have multiple domains and want to name the secret and certificate the name of the domain all while keeping my repo public and also making sense on my end when I run `k get certificates -A`

**Comment by stefanprodan** [comment]
Ok so if you consider some field in some random resource like Ingress a secret, how can any tool know this and hide it from the diff? The diff will only hides Kubernetes Secrets values when it compares 2 secrets objects, an Ingress or any other Kubernetes Kind besides Secret is not a secret.

**Comment by onedr0p** [comment]
That is a good question for sure and fits a very specific use-case. Since there isn't really a standard on this, maybe there could be a `exclude` sub-command on `diff`?

e.g. `kustomizer diff -f cluster/apps/velero/helm-release.yaml --exclude "*SECRET_*" --exclude "*NAS_*"`

**Comment by stefanprodan** [comment]
I'm not sure how is this useful to you, if someone can run `diff` on your cluster, then it can just do `kubectl get ingress` and find out the "secret" that way.

**Comment by onedr0p** [comment]
It would be neat to run this diff in a CI job with using a self-hosted GH runner. I am currently doing this with a [bash script and a custom github action](https://github.com/onedr0p/home-cluster/blob/main/.github/workflows/diff-helm-releases.yaml). That GH workflow produces the following output, [see this PR and the first comment attached](https://github.com/onedr0p/home-cluster/pull/2041) on it.

**Comment by stefanprodan** [comment]
Does your action connects to your cluster to build the diff?

**Comment by stefanprodan** [comment]
> kustomizer diff -f cluster/apps/velero/helm-release.yaml --exclude "*SECRET_*" --exclude "*NAS_*"

Wouldn't the exclude args show up in CI logs? I guess you're passing the actual secret value in there?

**Comment by onedr0p** [comment]
Currently no, but I could use a tool like [actions-runner-controller](https://github.com/actions-runner-controller/actions-runner-controller) to use a self-hosted runner in my cluster to run kustomizer.

**Comment by onedr0p** [comment]
> > kustomizer diff -f cluster/apps/velero/helm-release.yaml --exclude "_SECRET__" --exclude "_NAS__"
> 
> Wouldn't the exclude args show up in CI logs? I guess you're passing the actual secret value in there?

No I would only be passing in a regex or glob matching the variable name.

**Comment by stefanprodan** [comment]
Here is where the Kind detection happens https://github.com/stefanprodan/kustomizer/blob/main/pkg/manager/manager_diff.go#L56-L67 and here is how values are masked https://github.com/stefanprodan/kustomizer/blob/main/pkg/objectutil/fmt.go#L57. Making this work for any Kind would require some reflection? No idea what it entails.

**Comment by onedr0p** [comment]
I know this is probably outside the intended usecase of flux and kustomizer, but maybe something you can think about. It would solve some discussions on the flux repo.

https://github.com/fluxcd/flux2/discussions/820
https://github.com/fluxcd/flux2/discussions/1337

**Comment by stefanprodan** [comment]
The Flux CLI will have a `diff` command for Kustomizations, but like here it will not mask random things but only Kubernetes Secrets data values.

**Comment by onedr0p** [comment]
Neat! Maybe we can revisit that when Flux has that feature instead of adding it to kustomizer?

**Comment by stefanprodan** [comment]
> Maybe we can revisit this when Flux has that feature instead of adding it to kustomizer?

Sure

PS. Kustomizer is not suitable for diffing the things reconciled by Flux, especially if you have vars and other transformers in your Flux Kustomizations.
